const STOCKS_CONSTANTS = {
  STOCKS_INSTRUMENT_REQUEST: "STOCKS_INSTRUMENT_REQUEST",
  STOCKS_INSTRUMENT_RECEIVE: "STOCKS_INSTRUMENT_RECEIVE",
  STOCKS_INSTRUMENT_FAILURE: "STOCKS_INSTRUMENT_FAILURE",
};

export default STOCKS_CONSTANTS;
